# The following code was generated by Google Gemini from a prompt given to it
# by Paul Vickers, 03/03/2026.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
from scipy.signal import spectrogram

# Define the file path and signal parameters
file_path = (
    "Python\src\Datasets\Simulated_Data\WMC_Data_for_Mark\BFI-2\S_BFI_2_1_modified.csv"
)
Fs = 35000  # Sampling frequency (Hz) - consistent with other analysis
# Note from PV: I don't recall what the sampling frequency of Dan's data was. # You should probably change Fs to match Dan's sampling rate otherwise the reported frequency values will be misleading.

# Spectrogram parameters
nperseg_val = 1024  # Length of each segment (window size)
noverlap_val = 512  # Number of points to overlap between segments

try:
    # Load the CSV file
    df = pd.read_csv(file_path)

    if df.empty:
        raise ValueError("The CSV file is empty.")

    # Select the first column as the signal
    signal_data = pd.to_numeric(df.iloc[:, 0], errors="coerce").dropna().values

    if len(signal_data) == 0:
        raise ValueError("No valid numerical data found in the first column.")

    # Compute the spectrogram for the original signal
    f_spec_original, t_spec_original, Sxx_original = spectrogram(
        signal_data, fs=Fs, nperseg=nperseg_val, noverlap=noverlap_val
    )

    rows, cols = Sxx_original.shape

    # -----Stats across all frequencies----
    # Print rows & columns for clarity
    print("Rows", rows)
    print("Columns", cols)
    print(Sxx_original[:1])

    # Convert to Pandas dataframe
    df = pd.DataFrame(Sxx_original)
    spectral_mean = df.mean()
    rolling_global_mean = spectral_mean.rolling(window=3).mean()

    for i, value in rolling_global_mean.items():
        if pd.notna(value):
            print(value)
            time.sleep(0.1)

    # ----Stats across specific frequency band-----
    f_low = 2000
    f_high = 3000

    idx = np.where((f_spec_original >= f_low) & (f_spec_original <= f_high))[0]

    band_data = Sxx_original[idx, :].mean(axis=0)

    band_series = pd.Series(band_data)
    rolling_band_mean = band_series.rolling(window=3).mean()

    # Plot the spectrogram
    plt.figure(figsize=(12, 6))
    plt.pcolormesh(
        t_spec_original, f_spec_original, 10 * np.log10(Sxx_original), shading="gouraud"
    )
    plt.ylabel("Frequency [Hz]")
    plt.xlabel("Time [sec]")
    plt.title(
        f"Spectrogram of Original Signal (nperseg={nperseg_val}, noverlap={noverlap_val})"
    )
    plt.ylim(
        0, 5000
    )  # Adjust y-axis limit based on expected frequency range of the signal
    plt.colorbar(label="Intensity [dB]")
    plt.savefig("Spectrogram")
    plt.show()

    # Plot rolling mean of frequency band
    plt.figure(figsize=(12, 5))
    plt.plot(
        t_spec_original,
        rolling_global_mean,
        label="Global Mean (All Freq)",
        color="blue",
        linewidth=2,
    )
    plt.plot(
        t_spec_original,
        rolling_band_mean,
        label=f"Band Mean ({f_low}-{f_high}Hz)",
        color="orange",
        linestyle="--",
    )
    plt.xlabel("Time [sec]")
    plt.ylabel("Mean Amplitude")
    plt.title("Global mean vs specific band mean")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

    print("Combined operation (load, spectrogram) executed successfully.")

except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found. Please check the path.")
except pd.errors.EmptyDataError:
    print(f"Error: The file '{file_path}' is empty.")
except ValueError as e:
    print(f"Error: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")
